### ISSUE TITLE
Function Naming Convention

### ISSUE THREAD

**Issue by razyoboy** [Sirapakit/year-4-image#2]
Hello, I've noticed that in ```/Assignment-3/rgb-to-cmyk.py``` your function names are rather 'non-pythonic' as you utilized the camel case naming convention (```helloWorld```), instead of snake case (```hello_world```) convention, as per the PEP 8 style guide [here](https://peps.python.org/pep-0008/#function-and-variable-names).

Please let me know if you would be willing to accept my help in renaming these functions.
Thanks.

**Comment by Sirapakit** [comment]
Hi @razyoboy !
Firstly, I really appreciate your time and effort for checking my repository for this amazing class. I used to write typescript and javascript a lot in my summer intern period, so my habit maybe carry on from that. 
Your guidance and contribution will really help me improve my coding skill.
You can access [here](https://www.youtube.com/watch?v=dQw4w9W)
Thanks!
